name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and run tests
        run: |
          npm install
          npm test

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}  
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "${HOME}/gcloud.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud.json"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-gcp-project
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform apply -auto-approve

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
